---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dns-resolution-check
  namespace: kuberhealthy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dns-resolution-check
  namespace: kuberhealthy
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dns-resolution-check
  namespace: kuberhealthy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dns-resolution-check
subjects:
  - kind: ServiceAccount
    name: dns-resolution-check
    namespace: kuberhealthy
---
apiVersion: kuberhealthy.github.io/v2
kind: HealthCheck
metadata:
  name: dns-status-internal
  namespace: kuberhealthy
spec:
  runInterval: 2m
  timeout: 15m
  podSpec:
    spec:
      serviceAccountName: dns-resolution-check
      containers:
        - name: dns-resolution-check
          image: kuberhealthy/dns-resolution-check:sha-<short-sha>
          imagePullPolicy: IfNotPresent
          env:
            - name: HOSTNAME
              value: "kubernetes.default"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      restartPolicy: Never
